// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd_4tNMoiw_eOZPeOIt7VIc4bXtRn3NDs',
    appId: '1:83635710092:web:a7b306b972343662f973a9',
    messagingSenderId: '83635710092',
    projectId: 'quick-start-f1utter',
    authDomain: 'quick-start-f1utter.firebaseapp.com',
    storageBucket: 'quick-start-f1utter.appspot.com',
    measurementId: 'G-R7NNJ9CHP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdo529eyNkbuIvPaqgsrrai6rSrGeQp9E',
    appId: '1:83635710092:android:dcfd1515e2e026f3f973a9',
    messagingSenderId: '83635710092',
    projectId: 'quick-start-f1utter',
    storageBucket: 'quick-start-f1utter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDodw7IwMgBVVq_so4aeEYZnT22L3P-BtY',
    appId: '1:83635710092:ios:d888276cc465346af973a9',
    messagingSenderId: '83635710092',
    projectId: 'quick-start-f1utter',
    storageBucket: 'quick-start-f1utter.appspot.com',
    iosBundleId: 'com.example.quickStart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDodw7IwMgBVVq_so4aeEYZnT22L3P-BtY',
    appId: '1:83635710092:ios:0c3d64f2be04aca4f973a9',
    messagingSenderId: '83635710092',
    projectId: 'quick-start-f1utter',
    storageBucket: 'quick-start-f1utter.appspot.com',
    iosBundleId: 'com.example.quickStart.RunnerTests',
  );
}
